name: Deploy to Firebase Functions

on:
  push:
    branches:
      - deploy1

jobs:
  deploy:
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy Firebase Functions
        run: |
          firebase deploy --only functions
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}